---
- hosts: all
  become: yes

  tasks:
    # multiply by 1024
    - name: save memory as bytes
      set_fact:
        mem_bytes: "{{ ansible_memtotal_mb * 1024 * 1024}}"

    - name: touch the file
      file:
        path: /var/swapper
        state: touch
        owner: root
        group: root
        mode: '0600'
        attributes: "+C"

    - name: fallocate stuff
      command: fallocate -l "{{mem_bytes}}" /var/swapper

    - name: mkswap
      command: mkswap /var/swapper

    - name: turn swap on
      command: swapon /var/swapper

    - name: add swap to fstab
      lineinfile:
        dest: /etc/fstab
        backup: yes
        state: present
        line: "/var/swapper none swap sw 0 0"
    - block:
      - name: create directories for overrides
        file:
          path: "{{ item }}"
          state: directory
        loop:
          - /etc/systemd/system/systemd-logind.service.d
          - /etc/systemd/system/systemd-hibernate.service.d

      - name: add logind override
        blockinfile:
          path: /etc/systemd/system/systemd-logind.service.d/override.conf
          create: yes
          block: |
            [Service]
            Environment=SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1

      - name: add hibernate override
        blockinfile:
          path: /etc/systemd/system/systemd-hibernate.service.d/override.conf
          create: yes
          block: |
            [Service]
            Environment=SYSTEMD_BYPASS_HIBERNATION_MEMORY_CHECK=1

    - name: run test container
      containers.podman.podman_container:
        name: mytest
        image: fedora
        privileged: yes
          #interactive: yes
        detach: no
        rm: yes
        command: 
          - /bin/sh
          - -c
          - | 
              dnf upgrade -y &> /dev/null
              dnf install -y gcc wget &> /dev/null
              wget 'https://raw.githubusercontent.com/osandov/osandov-linux/61679ecd914d653bab14d0e752595e86b9f50513/scripts/btrfs_map_physical.c' &> /dev/null
              gcc -O2 -o btrfs_map_physical btrfs_map_physical.c &> /dev/null
              ./btrfs_map_physical /var/swapper | sed -n '2p' | awk '{print $NF}'
        state: started
        volume: /var/swapper:/var/swapper
      register: physical_swap_offset

    - name: set pso fact
      set_fact:
        pso: "{{ physical_swap_offset.stdout | trim }}"

    - name: output physical btrfs offset
      debug:
        msg: "{{ pso }}"

    - name: get pagesize
      command: getconf PAGESIZE
      register: ps

    - name: set page size fact
      set_fact:
        page_size: "{{ ps.stdout | trim }}"

    - name: output page size
      debug:
        msg: "{{ page_size }}"

    - name: calculate swap offset
      set_fact:
        swap_offset: "{{ (pso|int/page_size|int)|int }}"
          #swap_offset: "{{ (pso)|int / (page_size)|int) }}"
      register: swapo

    - name: output swap offset
      debug:
        msg: "{{ swapo }}"

    - name: get swap uuid
      command: findmnt -no UUID -T /var/swapper
      register: uuid

    - name: set swap_uuid fact
      set_fact:
        swap_uuid: "{{ uuid.stdout | trim }}"

    - name: set resume_args fact
      set_fact:
        resume_args: "resume=UUID={{ swap_uuid }} resume_offset={{ swap_offset }}"

    - name: output resume args
      debug:
        msg: "{{ resume_args }}"

    - name: update grub
      command: grubby --update-kernel=ALL --args={{ resume_args }}

    - name: add resume module to dracut
      lineinfile:
        path: /etc/dracut.conf.d/resume.conf
        create: yes
        line: 'add_dracutmodules+=" resume "'

    - name: update initramfs
      command: dracut -f
